### ISSUE TITLE
Picture frame contents not saved

### ISSUE THREAD

**Issue by dslake** [dslake/WorldDownloader#15]
[quote name='soccerguy3' timestamp='1354117152' post='19398943']
Hi Cubic

I just noticed that the picture frames and their contents are not saved
[/quote]

self explanatory.

**Comment by johnmlang** [comment]
I expect that this is due to Paintings and Item Frames being entities, and therefore unsaved unless they are in the area when the download is stopped.

**Comment by dslake** [comment]
Containers are entities too but they are TileEntities. TileEntities I think
are the type that don't move so they don't have a tracking range like mobs,
players and stuff on the ground do. This should be straightforward to fix
once I get into editing the mod again. I'm putting together a patch next
week for some other bugs so I'll look at this in that commit. Thanks.

**Comment by dslake** [comment]
Picture frame contents were being saved as long as the save was stopped while the picture was still within the tracking range. Now the picture contents are saved privately to the chunk data even if the server deletes the picture as it goes out of range.
