### ISSUE TITLE
Reduce Verbiosity in Chat

### ISSUE THREAD

**Issue by johnmlang** [dslake/WorldDownloader#16]
Version: 1.4.5

Feature Request:

World Downloader displays a message every time a chest, furnace, etc. is accessed, and several messages when traveling through portals.  Most of these messages are extra information that the user doesn't need to know and require no user response; they result in the chat log filled with unnecessary clutter.  

By default (or with a setting), the verbosity should be reduced.  The only status/debug messages that should be displayed are 'Download Started' when the download is begun, 'Saving...' when the user stops the download, and 'Download Complete' after the user-stopped download has completed.

All the other messages are secondary, and as a user, I don't know why I need to see them; there is no action I need to or could take after reading them.  But I do understand their value for development.

**Comment by cubic72** [comment]
Good tip, thanks. Many people asked why some chests were saved and some where not, etc. So I added in a message the explicitly states when a container contents is received from the server so it was clear when it happened. WHenever you change worlds, it saves the current world and then starts downloading the new world. I'll see what I can do to simplify the messaging or add a 'verbose' option for users who want to enable/disable it. Thanks.

**Comment by dslake** [comment]
The chat messages related to the saving chest contents and other entities has been removed. Also the messages describing the save process have been reduced to just start and end of the save.
