### ISSUE TITLE
Minecraft Freezes when downloading the world and using fireworks.

### ISSUE THREAD

**Issue by seen-one** [dslake/WorldDownloader#18]
So you make fireworks, start downloading the world and then use lots of fireworks. It will eventually freeze the game (Not crash) and make it unplayable. If you can't reproduce this issue, I might make a YouTube video.

**Comment by seen-one** [comment]
can others confirm this? Thanks.

**Comment by dslake** [comment]
Thanks for reporting this. Fireworks are an entity and in the latest version, entities are not removed so this likely causes the hang. I'll debug this and post a new version.

**Comment by seen-one** [comment]
Great!

**Comment by dslake** [comment]
I'll post a new version for 1.4.6 and comment in the forum when it's posted.
