### ISSUE TITLE
Restarts Download After Death/Teleport

### ISSUE THREAD

**Issue by CrazyCraftians** [dslake/WorldDownloader#19]
I was playing survival games on a cool map and I downloaded it but when I won and got teleported back I lost it. I dont know if if was Multiworld but I had a sad face :(

**Comment by nairol** [comment]
Sorry for your sad face :(

It's hard to guess the problem without more information like the name of the map, server, and what you meant by "I lost it".

Closing this bug for now. If you encounter similar problems with the current version of World Downloader, please reopen this bug and add as much information as possible.
