### ISSUE TITLE
Minecraft crashes on 1.4.6/1.4.7 with Multiworld Enabled/Disabled after putting in name

### ISSUE THREAD

**Issue by vegaobscura** [dslake/WorldDownloader#20]
---- Minecraft Crash Report ----
// Don't do that.

Time: 1/13/13 10:14 PM
Description: Updating screen events

java.lang.RuntimeException: Failed to check session lock, aborting
    at ahv.h(SourceFile:49)
    at ahv.<init>(SourceFile:35)
    at ahr.<init>(SourceFile:16)
    at ahs.a(SourceFile:78)
    at WDL.start(WDL.java:125)
    at auf.a(GuiIngameMenu.java:100)
    at aul.a(SourceFile:72)
    at aul.d(SourceFile:127)
    at aul.m(SourceFile:111)
    at net.minecraft.client.Minecraft.l(SourceFile:1086)
    at net.minecraft.client.Minecraft.J(SourceFile:582)
    at net.minecraft.client.Minecraft.run(SourceFile:534)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at ahv.h(SourceFile:49)
    at ahv.<init>(SourceFile:35)
    at ahr.<init>(SourceFile:16)
    at ahs.a(SourceFile:78)
    at WDL.start(WDL.java:125)
    at auf.a(GuiIngameMenu.java:100)
    at aul.a(SourceFile:72)
    at aul.d(SourceFile:127)
    at aul.m(SourceFile:111)

-- Affected screen --
Details:
    Screen name: auf

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [ays['mchaydu'/2844, l='MpServer', x=467.60, y=21.62, z=820.76]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (427,24,805), Chunk: (at 11,1,5 in 26,50; contains blocks 416,0,800 to 431,255,815), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Level time: 449102662 game time, 449328036 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 35 total; [pe['Sheep'/2852, l='MpServer', x=469.75, y=13.00, z=775.41], ays['mchaydu'/2844, l='MpServer', x=467.60, y=21.62, z=820.76], pd['Pig'/2853, l='MpServer', x=475.16, y=14.00, z=767.19], pd['Pig'/2854, l='MpServer', x=501.72, y=20.00, z=872.50], pe['Sheep'/2855, l='MpServer', x=471.24, y=14.00, z=759.69], ow['Bat'/2848, l='MpServer', x=500.75, y=21.00, z=857.25], ow['Bat'/2849, l='MpServer', x=494.99, y=22.80, z=846.25], ow['Bat'/2850, l='MpServer', x=497.55, y=22.76, z=846.25], pd['Pig'/2851, l='MpServer', x=484.84, y=21.00, z=854.06], pd['Pig'/2860, l='MpServer', x=405.43, y=19.00, z=832.80], pd['Pig'/2862, l='MpServer', x=520.97, y=21.00, z=760.03], pd['Pig'/2863, l='MpServer', x=547.09, y=18.00, z=826.22], pe['Sheep'/2856, l='MpServer', x=483.59, y=12.00, z=762.47], oz['Cow'/2857, l='MpServer', x=540.50, y=18.00, z=812.63], oz['Cow'/2858, l='MpServer', x=489.91, y=18.00, z=892.98], pd['Pig'/2859, l='MpServer', x=515.03, y=20.50, z=770.09], oz['Cow'/2865, l='MpServer', x=482.03, y=18.00, z=896.03], mg['Painting'/2884, l='MpServer', x=539.50, y=24.50, z=921.06], oy['Chicken'/2866, l='MpServer', x=389.67, y=19.00, z=795.38], mg['Painting'/2883, l='MpServer', x=543.50, y=24.50, z=925.06], mg['Painting'/2886, l='MpServer', x=538.50, y=24.00, z=922.06], mg['Painting'/2885, l='MpServer', x=540.94, y=24.50, z=922.50], mg['Painting'/2893, l='MpServer', x=540.94, y=24.00, z=932.50], mg['Painting'/2891, l='MpServer', x=544.94, y=24.50, z=926.50], mg['Painting'/2894, l='MpServer', x=541.50, y=24.50, z=931.94], mg['Painting'/2883, l='MpServer', x=543.50, y=24.50, z=925.06], mg['Painting'/2886, l='MpServer', x=538.50, y=24.00, z=922.06], mg['Painting'/2884, l='MpServer', x=539.50, y=24.50, z=921.06], mg['Painting'/2885, l='MpServer', x=540.94, y=24.50, z=922.50], mg['Painting'/2891, l='MpServer', x=544.94, y=24.50, z=926.50], mg['Painting'/2894, l='MpServer', x=541.50, y=24.50, z=931.94], mg['Painting'/2893, l='MpServer', x=540.94, y=24.00, z=932.50], ow['Bat'/2847, l='MpServer', x=500.28, y=23.04, z=851.50], oz['Cow'/2846, l='MpServer', x=458.00, y=19.00, z=848.06], oz['Cow'/2845, l='MpServer', x=467.59, y=20.00, z=815.38]]
    Retry entities: 0 total; []
Stacktrace:
    at ayp.a(WorldClient.java:481)
    at net.minecraft.client.Minecraft.b(SourceFile:1871)
    at net.minecraft.client.Minecraft.run(SourceFile:543)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.4.6
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_03, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 412076920 bytes (392 MB) / 514523136 bytes (490 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -Xms512m -Xmx1024m
    AABB Pool Size: 7817 (437752 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
    Suspicious classes: GuiWDLMultiworldSelect, GuiWDLMultiworld, GuiWDL, ...]
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    LWJGL: 2.4.2
    OpenGL: GeForce GTX 570/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    Is Modded: Very likely; Jar signature invalidated
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 1061 (59416 bytes; 0 MB) allocated, 12 (672 bytes; 0 MB) used

**Comment by nairol** [comment]
Closing because version no longer supported.
Please reopen if the bug is still there in the latest version.
