### ISSUE TITLE
Minecraft Crashes

### ISSUE THREAD

**Issue by jonathanmajh** [dslake/WorldDownloader#32]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 08/07/13 2:36 PM
Description: Initializing game

java.lang.VerifyError: (class: blq, method: a signature: (III)V) Incompatible argument to function
    at ats.O(SourceFile:391)
    at ats.d(SourceFile:599)
    at net.minecraft.client.main.Main.main(SourceFile:101)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at ats.O(SourceFile:391)

-- Initialization --
Details:
Stacktrace:
    at ats.d(SourceFile:599)
    at net.minecraft.client.main.Main.main(SourceFile:101)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Windows XP (x86) version 5.1
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 27726400 bytes (26 MB) / 64503808 bytes (61 MB) up to 1013645312 bytes (966 MB)
    JVM Flags: 1 total; -Xmx999m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: No suspicious classes found.
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: 1.6.2save
    LWJGL: 2.9.0
    OpenGL: Intel 865G GL version 1.3.0 - Build 4.14.10.4396, Intel
    Is Modded: Very likely; Jar signature invalidated
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by dslake** [comment]
The classes that it mentions in your stack trace (main, ats, blq) are not part of World Downloader and are not modified by World Downloader. Do you have other mods installed with WDL? This is with 1.6.1, right? Not the 1.6.2 that came out this morning?

**Comment by nairol** [comment]
Closing because needed info was not provided and version no longer supported.
