### ISSUE TITLE
Won't Launch

### ISSUE THREAD

**Issue by willbootle** [dslake/WorldDownloader#33]
I have followed the install directions to a "T", but I am receiving this error whenever I try to launch minecraft.  

---- YOU CAN CLOSE THIS LAUNCHER IF THE GAME STARTED OK ----
---- YOU CAN CLOSE THIS LAUNCHER IF THE GAME STARTED OK ----
---- YOU CAN CLOSE THIS LAUNCHER IF THE GAME STARTED OK ----
---- (We'll do this automatically later ;D) ----
Client> Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraft/client/main/Main
Client> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.main.Main
Client>     at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
Client>     at java.security.AccessController.doPrivileged(Native Method)
Client>     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
Client>     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
Client>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
Client>     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Game ended with bad state (exit code 1)
Deleting /Users/Will/Library/Application Support/minecraft/versions/1.6.2.wdl/1.6.2.wdl-natives-1374079888475763000

I have tried looking for solutions and I have been going through the code, however I am not the best Java coder.  I am much more of a C++ and [Obj C] Person.

Thanks for any help!
Will

**Comment by dslake** [comment]
This has nothing to do with WDL or any of the Minecraft code. The launcher isn't even able to find the Main method to start up Minecraft. See where it says "java.lang.NoClassDefFoundError: net/minecraft/client/main/Main". You must have messed up your jarfile or directory structure somehow. Try using MCPatcher instead of doing it manually.

**Comment by willbootle** [comment]
Thanks.  It was the structure that was corrupted from manually editing the jar.  Again thanks for the help.
