### ISSUE TITLE
Launcher tries to launch the game, fails, gives launcher screen again.

### ISSUE THREAD

**Issue by dj--jg** [dslake/WorldDownloader#35]
Refreshing local version list...
Launcher 1.2.7 (through bootstrap 5) started on osx...
Current time is Oct 21, 2013 5:05:12 PM
System.getProperty('os.name') == 'Mac OS X'
System.getProperty('os.version') == '10.6.8'
System.getProperty('os.arch') == 'x86_64'
System.getProperty('java.version') == '1.6.0_51'
System.getProperty('java.vendor') == 'Apple Inc.'
System.getProperty('sun.arch.data.model') == '64'
Refreshing remote version list...
Refresh complete.
Loaded 4 profile(s); selected 'dj__jgWDL'
Refreshing auth...
Logging in with access token
Delta time to compare resources: 2431 ms 
Download job 'Resources' skipped as there are no files to download
Job 'Resources' finished successfully
Getting syncinfo for selected version
Queueing library & version downloads
Download job 'Version & Libraries' started (8 threads, 19 files)
Finished downloading /Users/****_/Library/Application Support/minecraft/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/**_**/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/****_/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/**_**/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/****_/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/**_**/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-osx.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/****_/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/**_**/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/****_/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/**_**/Library/Application Support/minecraft/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/****_/Library/Application Support/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/**_**/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/****_/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/**_**/Library/Application Support/minecraft/libraries/com/google/guava/guava/14.0/guava-14.0.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/****_/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/**_**/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/****_/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/**_**/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar for job 'Version & Libraries': Used own copy as it matched etag
Finished downloading /Users/****_/Library/Application Support/minecraft/versions/1.6.4.WDL/1.6.4.WDL.jar for job 'Version & Libraries': Couldn't connect to server (responded with 403) but have local file, assuming it's good
Job 'Version & Libraries' finished successfully
Launching game
Looking for old natives to clean up...
Unpacking natives to /Users/**_**/Library/Application Support/minecraft/versions/1.6.4.WDL/1.6.4.WDL-natives-1382367922859216000
Launching in /Users/****_/Library/Application Support/Vanilla
Running /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java -Xdock:icon=/Users/**_**/Library/Application Support/minecraft/assets/icons/minecraft.icns -Xdock:name=Minecraft -Xmx2G -Djava.library.path=/Users/****_/Library/Application Support/minecraft/versions/1.6.4.WDL/1.6.4.WDL-natives-1382367922859216000 -cp /Users/**_**/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar:/Users/****_/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/Users/**_**/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/Users/****_/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/Users/**_**/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/Users/****_/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/Users/**_**/Library/Application Support/minecraft/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar:/Users/****_/Library/Application Support/minecraft/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar:/Users/**_**/Library/Application Support/minecraft/libraries/com/google/guava/guava/14.0/guava-14.0.jar:/Users/****_/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:/Users/**_**/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/****_/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/**_**/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/****_/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar:/Users/**_**/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar:/Users/****_/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar:/Users/**_**/Library/Application Support/minecraft/versions/1.6.4.WDL/1.6.4.WDL.jar net.minecraft.client.main.Main --username dj__jg --session token:25f0c23559da48fba70d26445cb67ceb:4ec9a8a9a81b4fbea3af443fa1241087 --version 1.6.4.WDL --gameDir /Users/****_/Library/Application Support/Vanilla --assetsDir /Users/**_**/Library/Application Support/minecraft/assets --width 1600 --height 1000
Client> Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraft/client/main/Main
Client> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.main.Main
Client>     at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
Client>     at java.security.AccessController.doPrivileged(Native Method)
Client>     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
Client>     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
Client>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
Client>     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Game ended with bad state (exit code 1)
Ignoring visibility rule and showing launcher due to a game crash
Deleting /Users/*****/Library/Application Support/minecraft/versions/1.6.4.WDL/1.6.4.WDL-natives-1382367922859216000

**Comment by dslake** [comment]
This line:

> Exception in thread "main" java.lang.NoClassDefFoundError: net/minecraft/client/main/Main

Means that you modified your install files in a way that the launcher cannot find the minecraft binary. If "Main" isn't found, then nothing can work. Please post at the forum if you still have trouble with the installation.
