### ISSUE TITLE
After downloading downloads forever...

### ISSUE THREAD

**Issue by Ncraftmate** [dslake/WorldDownloader#39]
Yeah and if i leave the game and go to singleplayer world it cuts the downloaded world into half...
http://imgur.com/RAdtQf5

**Comment by dslake** [comment]
Are you using the latest version from January 18th? If so, I can upload a debug version for you tomorrow evening that will give me more information about what it's doing.

**Comment by Ncraftmate** [comment]
Yes i am using the latest version which is 1.7.2 i believe.

**Comment by dslake** [comment]
I've made 4 different versions for 1.7.2. Just doublecheck you are using the latest one from the forum link. One option, ff the server you are using is public, you can PM me the IP and I'll try to reproduce the problem you are seeing. If you don't see any error messages in the chat or in the java console, then I'm not sure what the problem could be. When I get a chance, I can also make a debug version of the mod that will spew lots of inner details about what's going on and that might give a clue.

**Comment by Ncraftmate** [comment]
Well ok then heres the ip of the server spawn/hub i am trying to get: hub.prxcraft.com
I will try to do what you say but if none of the things work i will reply asap

**Comment by Ncraftmate** [comment]
Hmm that weird i downloaded the direct connect link and reinstall it with that using magic laucher now it works perfectly well thank you anyways :D VERY HELPFUL!

**Comment by dslake** [comment]
OK, so you are good to go? The adfly and direct links should point to the exact same file, but I'll double check that.

**Comment by nairol** [comment]
Looks like this is solved?
Please reopen if it's not.
