### ISSUE TITLE
Wont run in 1.7.4

### ISSUE THREAD

**Issue by Kiersters** [dslake/WorldDownloader#40]
When I try to run minecraft after doing everything you instructed on how to install world downloader, this is the crash report I get:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 1/26/14 7:23 PM
Description: Initializing game

java.lang.VerifyError: (class: bog, method: <init> signature: ()V) Incompatible argument to function
    at azi.ad(SourceFile:384)
    at azi.f(SourceFile:696)
    at net.minecraft.client.main.Main.main(SourceFile:152)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at azi.ad(SourceFile:384)

-- Initialization --
Details:
Stacktrace:
    at azi.f(SourceFile:696)
    at net.minecraft.client.main.Main.main(SourceFile:152)

-- System Details --
Details:
    Minecraft Version: 1.7.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_04, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 61922432 bytes (59 MB) / 128385024 bytes (122 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: 1.7.4.wdl
    LWJGL: 2.9.1
    OpenGL: AMD RADEON HD 6450 GL version 4.1.10834 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: []
Current Language: ~~ERROR~~ NullPointerException: null
Profiler Position: N/A (disabled)
Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
Anisotropic Filtering: Off (1)
```

PS> I tried it 5 times

**Comment by dslake** [comment]
The mod is for 1.7.2. Look at the title of the forum thread and the name of the zip file you downloaded.
