### ISSUE TITLE
Game crashes when I press Download This World

### ISSUE THREAD

**Issue by Craftboy360** [dslake/WorldDownloader#41]
If I am in a server and I'm thinking, wow, I want this world too, the mod don't let me download it by doing this: CRASH! So plz fix it, because I want some worlds so much! (Sorry for bad english)

**Comment by dslake** [comment]
I can't help you unless you tell me at least:

Which version of Minecraft are you running? 
Which version of World Downloader are you running? 
Please include your crash report from the console.

**Comment by nairol** [comment]
Closing because needed info was not provided.
