### ISSUE TITLE
[v2 beta3] Warp on a MP server causes crash. Single player file has nether when not on server.

### ISSUE THREAD

**Issue by dslake** [dslake/WorldDownloader#5]
Sometimes when I warp on a MP server I crash. When I long on to the map in SP, I'm traped in the stone in the netherworld. None of the servers have netherworld turned on.. this happened two times today after installing V2 beta 3.

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 9/6/12 1:02 AM
Description: Unexpected error

java.lang.RuntimeException: World Downloader: Couldn't stop download! Check your worlds!
at WDL.onWorldLoad(WDL.java:157)
at atd.a(WorldClient.java:150)
at asv.a(NetClientHandler.java:627)
at cn.a(SourceFile:97)
at bb.b(SourceFile:333)
at asv.d(NetClientHandler.java:91)
at atd.b(WorldClient.java:63)
at net.minecraft.client.Minecraft.l(SourceFile:1261)
at net.minecraft.client.Minecraft.J(SourceFile:583)
at net.minecraft.client.Minecraft.run(SourceFile:535)
at java.lang.Thread.run(Unknown Source)

Relevant Details:
- Minecraft Version: 1.3.2
- Operating System: Windows 7 (amd64) version 6.1
- Java Version: 1.7.0_07, Oracle Corporation
- Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
- Memory: 238738072 bytes (227 MB) / 531103744 bytes (506 MB) up to 954466304 bytes (910 MB)
- JVM Flags: 2 total; -Xms512m -Xmx1024m
- ModLoader: Mods loaded: 8
  ModLoader 1.3.2
  mod_ModLoaderMp 1.3.2v1
  mod_TooManyItems 1.3.2 2012-08-16
  mod_cjb_cheats 6.3.5
  mod_cjb_main 6.3.5
  mod_cjb_minimap 6.3.5
  mod_cjb_moreinfo 6.3.5
  mod_cjb_x_ray 6.3.5
- LWJGL: 2.8.4
- OpenGL: ATI Radeon HD 5700 Series GL version 4.2.11762 Compatibility Profile Context, ATI Technologies Inc.
- Is Modded: Very likely
- Type: Client
- Texture Pack: Default
- Profiler Position: N/A (disabled)
- World MpServer Entities: 15 total;  , jz , jz , jz , jz , aur , jz , jz , jz , jz , jz , jz , jz , jz , jz ]
- World MpServer Players: 2 total;  , aur ]
- World MpServer Chunk Stats: MultiplayerChunkCache: 0
- Forced Entities: 29 total;  , jz , jz , jz , aur , jz , jz , jz , jz , jz , jz , jz , jz , jz , jz , jz , jz , jz , jz , jz , jz , aur , atg , jz , jz , jz , jz , jz , jz ]
- Retry Entities: 0 total; []

**Comment by nairol** [comment]
I think we can close this.
