### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by ghost** [dslake/WorldDownloader#53]
sorry XD I dont have a minecraft forum account so I cant ask there. When will it be updated?

**Comment by nairol** [comment]
https://github.com/dslake/WorldDownloader/releases/download/1.7.10/World.Downloader.1.7.10a.zip

I have updated it to 1.7.10 but I cannot edit the first post in the forum thread. I have repeatedly posted this in the thread. Please read at least the last page before asking for updates.

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=ViYcDHITSmM sorry
