### ISSUE TITLE
Crashes immediately after installing (MAC)

### ISSUE THREAD

**Issue by louis-lau** [dslake/WorldDownloader#8]
java.lang.VerifyError: (class: net/minecraft/client/Minecraft, method: a signature: ()V) Incompatible argument to function
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2427)
    at java.lang.Class.getMethod0(Class.java:2670)
    at java.lang.Class.getMethod(Class.java:1603)
    at magic.launcher.Launcher.main(Unknown Source)

**Comment by dslake** [comment]
How are you installing the mod? It doesn't look like any World Downloader
code is running yet when it crashes. Do you have other mods installed that
may be incompatible?

On Wednesday, September 19, 2012, louis-lau wrote:

> java.lang.VerifyError: (class: net/minecraft/client/Minecraft, method: a
> signature: ()V) Incompatible argument to function
> at java.lang.Class.getDeclaredMethods0(Native Method)
> at java.lang.Class.privateGetDeclaredMethods(Class.java:2427)
> at java.lang.Class.getMethod0(Class.java:2670)
> at java.lang.Class.getMethod(Class.java:1603)
> at magic.launcher.Launcher.main(Unknown Source)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dslake/WorldDownloader/issues/8.

## 

danthedad

**Comment by louis-lau** [comment]
no, i unzipped the minecraft.jar, put the class files in and deleted the META-INF folder i renamed the folder to minecraft.jar (that's how it usually works on mac) thanks for the fast reply :)

**Comment by louis-lau** [comment]
PS. i got the error report using magic launcher

**Comment by louis-lau** [comment]
and when i try the default launcher it just goes black

**Comment by louis-lau** [comment]
nvr mind, i was just being dumb
